### ISSUE TITLE
[Install] build from source error

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#154] opened 2023-04-11 08:37 UTC
If I build from source (following this page https://kaihsinwu.gitlab.io/Cytnx_doc/adv_install.html, and use the default Install.sh), I got the following errors:

The following tests FAILED:
146 - Svd.U1_sym_test (Failed)
147 - Svd.Z2_sym_test (Failed)
152 - Svd.none_isU_isVT (Failed)

**Comment by jeffry1829** [comment] 2023-04-13 07:56
Sorry, but I can't reproduce it.
May I check your current branch and commit?
Thanks!

**Comment by chiamin** [comment] 2023-04-13 09:15
I am not sure how to do it. This is the output of git log -1

commit d97baaa99f21accba1fe3d35bda42498f1aefa0f (HEAD -> master,
origin/master, origin/HEAD)
Author: jeffry1829 ***@***.***>
Date:   Mon Apr 10 09:48:12 2023 +0800

And the attachment is the Install.sh I used (the default one).


jeffry1829 ***@***.***> 於 2023年4月13日 週四 下午3:56寫道：

**Comment by chiamin** [comment] 2023-04-14 03:01
I am using Ubuntu

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Comment by kaihsin** [comment] 2023-04-21 13:45
This seems to be related to BlockUniTensor when is_diag = true, currently investigating.

**Comment by kaihsin** [comment] 2023-04-25 05:26
Could you try to set the:

`
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
`
and see if the errors go away? We suspect it is something related to MKL or hptt

**Comment by kaihsin** [comment] 2023-04-25 05:49
Also, please check 

1. All the mkl packages (mkl, mkl-service, mkl-include) installed from conda are from conda-forge channel.
    -> if not, set conda-forge to top priority and conda update mkl
2. check from `conda list` if _openmp_mutex  is llvm not gnu.

**Comment by chiamin** [comment] 2023-04-25 06:29
I pull the newest version and can now compile successfully *with and
without* export MKL_NUM_THREADS=1 export OMP_NUM_THREADS=1, and
with -DUSE_HPTT=ON.

Kai-Hsin Wu ***@***.***> 於 2023年4月25日 週二 下午1:49寫道：

**Comment by kaihsin** [comment] 2023-04-25 06:37
Cool. 

Just to make sure, the newest version of cytnx or newest version of mkl? 

There are two things we found from our investigation that related to this issue:

1. We found a bug in the Svd testing file (not the library), and we fixed that 
2. the conflict of mkl packages, and openmp_mutex will also cause this error.

**Comment by chiamin** [comment] 2023-04-25 06:51
The newest Cytnx and I did not touch MKL. Here are the MKL information in
conda list

mkl                       2022.1.0           hc2b9512_224
mkl-include               2023.0.0         h84fe81f_26648    conda-forge
mkl-service               2.4.0            py38h80f09db_0    conda-forge

Kai-Hsin Wu ***@***.***> 於 2023年4月25日 週二 下午2:37寫道：

**Comment by kaihsin** [comment] 2023-04-25 06:54
OK. So updated mkl will resolve the issue. Previously my mkl is on 2021. I will close this

**Closed by kaihsin** 2023-04-25 06:54 UTC
Labels: bug, Top priority
